
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Conference' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Conference
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'XLPagerTabStrip', '~> 7.0'
  pod 'Google/SignIn'
  pod 'IQKeyboardManager'
  pod 'Alamofire', '~> 4.4'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Eureka'
  pod 'SwiftyJSON'

  target 'ConferenceTests' do
    # Pods for testing
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'XLPagerTabStrip', '~> 7.0'
  pod 'Google/SignIn'
  pod 'IQKeyboardManager'
  pod 'Alamofire', '~> 4.4'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Eureka'
  pod 'SwiftyJSON'
  end

end
