# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Conference' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Conference
  pod 'XLPagerTabStrip', '~> 7.0'
  pod 'Google/SignIn'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'IQKeyboardManager'
  pod "PromiseKit", "~> 4.0"
  pod 'Alamofire', '~> 4.4'
end
